# Generated by Django 4.2.7 on 2025-11-23 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('pdf', 'PDF')], default='text', max_length=20)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('gemini_analysis', models.JSONField(blank=True, default=dict)),
                ('extracted_style_signals', models.JSONField(blank=True, default=dict)),
                ('extracted_facts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WritingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_sentence_length', models.FloatField(default=15.0)),
                ('tone_formality', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('professional', 'Professional'), ('academic', 'Academic')], default='professional', max_length=50)),
                ('vocabulary_keywords', models.JSONField(blank=True, default=list)),
                ('signature_phrases', models.JSONField(blank=True, default=list)),
                ('sentence_structure_patterns', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('generated', 'Generated'), ('inferred', 'Inferred')], default='upload', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['user', 'key'], name='api_persona_user_id_d7fe5c_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('detected_from_sample', models.BooleanField(default=True)),
                ('memory_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='api.documentmemory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_experie_user_id_c697bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentmemory',
            index=models.Index(fields=['user', '-created_at'], name='api_documen_user_id_606cfa_idx'),
        ),
    ]
