# Generated by Django 4.2.7 on 2025-11-23 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_sample_file', models.FileField(blank=True, null=True, upload_to='voice_samples/')),
                ('voice_sample_url', models.URLField(blank=True, null=True)),
                ('voice_clone_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tts_service', models.CharField(choices=[('web_speech', 'Web Speech API'), ('elevenlabs', 'ElevenLabs'), ('azure', 'Azure Speech'), ('google', 'Google Cloud TTS')], default='web_speech', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
