# Generated by Django 4.2.7 on 2025-11-24 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_voiceprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('max_requests_per_day', models.IntegerField(default=50)),
                ('requests_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_share_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='api_voicesh_token_fbf818_idx'), models.Index(fields=['user', 'is_active'], name='api_voicesh_user_id_3188c6_idx')],
            },
        ),
    ]
